hingston/7-billion-humans-solutions

- Solutions/Year 26 - Bugdet Bragade (Speed)
Trick was to avoid wasting time on error reports, other speed solutions actually exploit the time it takes to gripe. =P
> Create Year 26 - Bugdet Bragade (Speed)

- Year 26 - Bugdet Bragade 2 (Size)
> Create Year 26 - Bugdet Bragade 2 (Size)

- Solutions/Year 25 - My First Shredding Memory (speed)
> Create Year 25 - My First Shredding Memory (speed)

- Solutions/Year 30: Fill The Floor (speed)
The smelly humans return to their last drop before finding a new square, solves the random walk problem.
> Create Year 30: Fill The Floor (speed)

- Solutions99+/Year 07 - Collation Station (speed).txt
> Update Year 07 - Collation Station (speed).txt

- Solutions99+/Year 07 - Collation Station (size).txt
> Update Year 07 - Collation Station (size).txt

- Solutions99+/Year 10 - Emergency Escapades (size).txt
> Update Year 10 - Emergency Escapades (size).txt

- Solutions99+/Year 10 - Emergency Escapades (speed).txt
> Update Year 10 - Emergency Escapades (speed).txt

- Solutions99+/Year 11 - Injection Sites 1 (speed).txt
> Update Year 11 - Injection Sites 1 (speed).txt

- Solutions99+/Year 15 - Shred Lines (size).txt
> Update Year 15 - Shred Lines (size).txt

- Solutions99+/Year 15 - Shred Lines (speed).txt
> Update Year 15 - Shred Lines (speed).txt

- Solutions99+/Year 30 - Fill the Floor (size).txt
Solution is broken with the step inside the if-function.
> Update Year 30 - Fill the Floor (size).txt

- Solutions99+/Year 66 - Decimal Counter (Size)
> Create Year 66 - Decimal Counter (Size)

- Solutions99+/Year 68 - Goodbye Humans (size)
> Create Year 68 - Goodbye Humans (size)

- Solutions99+/Year 20 - Reverse Line (speed).txt
> Create Year 20 - Reverse Line (speed).txt

- Solutions99+/Year 21 - Big Data (speed).txt
> Create Year 21 - Big Data (speed).txt

- Solutions99+/Year 22 - Number Royale (size).txt
> Update Year 22 - Number Royale (size).txt

- Solutions99+/Year 22 - Number Royale (speed).txt
I think this may be slightly faster. Every now and then it gets an average of 6 seconds
> Update Year 22 - Number Royale (speed).txt

- Solutions99+/Year 24 - Budget Brigade 1 (speed).txt
> Update Year 24 - Budget Brigade 1 (speed).txt

- Solutions99+/Year 25 - My First Shredding Memory (speed).txt
> Update Year 25 - My First Shredding Memory (speed).txt

- Solutions99+/Year 26 - Bugdet Bragade 2 (Size).txt
> Update Year 26 - Bugdet Bragade 2 (Size).txt

- Solutions99+/Year 26 - Bugdet Bragade 2 (Speed).txt
> Update Year 26 - Bugdet Bragade 2 (Speed).txt

- Solutions99+/Year 26 - Bugdet Brigade 2 (Size).txt
Year 26 7i size - credit to https://www.twitch.tv/psam/ , posted with permission
> Update Year 26 size to 7i

- Solutions99+/Year 42 - Important Email Organization (size).txt
Not 100%, but the fails are rare enough to be >99%
> Improve Year 42  -  Important Email Organization (size) to 10i

- Solutions99+/Year 58 - Good Neighbors (speed).txt
Improvement of WEGFan's solution
> Improve Year 58  -  Good Neighbors (speed) to 3s

- README.md
Icon was a cross, but the solution meets the criteria so changed it to a tick
> Year 30 size challenge is 6

- Solutions99+/Year 36 - Seek and Destroy 2 (speed).txt
Remember the three smallest numbers in the column rather than one at a time.
> Year 36 - Speed - 101s

- Solutions99+/Year 44 - Unique Fashion Party (speed).txt
Removed an unnecessary if condition and removed nearest to get under the size goal.
> Year 44 - Size (10/11) & Speed (59s)

- README.md
> Level names on the contributors table redirect to the solution

- Solutions99+/Year 55 - Data Flowers (speed).txt
Made it both a bit shorter and much more reliable. In theory it's not 5s in 100% of cases, but I couldn't produce a 6s result.
> Improve Year 55  -  Data Flowers (speed)

- Solutions99+/Year 43 - Multiplication Table (speed).txt
> Year 43 Multiplication Table (speed, 27s)

- Solutions50+/Year 57 - Neighborly Sweeper (size).txt
- Solutions99+/Year 57 - Neighborly Sweeper (speed).txt
I seriously doubt if it's possible to reach size OCD+ score with 99+% success rate.
> Year 57 Neighborly Sweeper size(50+%) and speed

- Solutions99+/Year 26 - Budget Brigade 2 (speed).txt
> Update Year 26 - Budget Brigade 2 (speed).txt

- Solutions99+/Year 53 - 100 Cubes on the Floor (speed).txt
> Update Year 53 - 100 Cubes on the Floor (speed).txt

- Solutions99+/Year 30 - Fill the Floor (speed).txt
> Update Year 30 - Fill the Floor (speed).txt

- Solutions99+/Year 31 - Checkerboard Organization (speed).txt
> Update Year 31 - Checkerboard Organization (speed).txt

- Solutions99+/Year 43 - Multiplication Table (speed).txt
really similiar to 24s 100 cubes on the floor solution.
> Update Year 43 - Multiplication Table (speed).txt

- Solutions99+/Year 63 - Defrag Disordered (speed).txt
thx to commonnickname for adding a foreachdir trick here
> Update Year 63 - Defrag Disordered (speed).txt

- Solutions99+/Defrag Ordered (speed)
> Create Defrag Ordered (speed)

- Solutions99+/Year 64 - Binary Counter (size).txt
> Update Year 64 - Binary Counter (size).txt

- Solutions99+/Year 06 - Little Exterminator 1 (size).txt
a lot simplier one, but still 8i
> Update Year 06 - Little Exterminator 1 (size).txt

- Solutions99+/Defrag Ordered (speed)
> Update Defrag Ordered (speed)

- Solutions99+/Year 09 - Dynamic Angles (speed).txt
> Update Year 09 - Dynamic Angles (speed).txt

- Solutions99+/Year 16 - Little Exterminator 2 (size).txt
faster (took commonnickname's solution as a starting point)
> Update Year 16 - Little Exterminator 2 (size).txt

- Solutions99+/Year 16 - Little Exterminator 2 (speed).txt
> Update Year 16 - Little Exterminator 2 (speed).txt

- Solutions99+/Year 20 - Reverse Line (speed).txt
> Update Year 20 - Reverse Line (speed).txt

- Solutions99+/Year 65 - Defrag Ordered (speed).txt
> Update Year 65 - Defrag Ordered (speed).txt

- Solutions99+/Year 36 - Seek and Destroy 2 (speed).txt
shorter (obviously took the previous solution as a starting point)
> Update Year 36 - Seek and Destroy 2 (speed).txt

- Solutions99+/Year 19 - Content Creators Bug Fix (both).txt
> Update Year 19 - Content Creators Bug Fix (both).txt

- Solutions99+/Year 25 - My First Shredding Memory (size).txt
In collaboration with n05ucc4u
> Improve Year 25  -  My First Shredding Memory (speed) to 129s

- SolutionsLowPercent/Year 56 - Local Maximums (both)
> Create Year 56 - Local Maximums (both)

- SolutionsLowPercent/Year 34 - Seek and Destroy 1 (speed)
> Create Year 34 - Seek and Destroy 1 (speed)

- Solutions99+/Year 38 - Seek and Destroy 3 (speed).txt
not 100%, but the chance of failure is very low
> Improve Year 38  -  Seek and Destroy 3 (speed) to 11s

- Solutions99+/Year 21 - Big Data (size).txt
> Improve Year 21 - Big Data (size) to 5i

- Solutions99+/Year 21 - Big Data (speed).txt
Over 100 runs: 
16s - 1x; 
17s - 8x; 
18s - 21x; 
19s - 33x; 
20s - 22x; 
21s - 12x; 
22s - 2x. 
Average 19.13s; 
Median 19s; 
Mode 19s; 
Standard deviation 1.23
> Improve Year 21 - Big Data (speed) to 17-21 s

- Year 47 - Automated Pleasantries (speed)
> Create Year 47 - Automated Pleasantries (speed)

- Solutions99+/Year 32 - Creative Writhing (speed).txt
shorter (took the previous solution as a starting point)
> Update Year 32 - Creative Writhing (speed).txt

- Solutions99+/Year 04 - Long Distance Delivery (size).txt
> Update Year 04 - Long Distance Delivery (size).txt

- Solutions99+/Year 09 - Dynamic Angles (size).txt
> Update Year 09 - Dynamic Angles (size).txt

- Solutions99+/Year 11 - Injection Sites 1 (size).txt
faster (by less than a second)
> Update Year 11 - Injection Sites 1 (size).txt

- Solutions99+/Year 54 - Terrain Leveler (size).txt
> Update Year 54 - Terrain Leveler (size).txt

- SolutionsLowPercent/Year 54 - Terrain Leveler (speed)
commonnickname found it earlier
> Create Year 54 - Terrain Leveler (speed)

- Solutions99+/Year 24 - Budget Brigade 1 (size).txt
> Update Year 24 - Budget Brigade 1 (size).txt

- Solutions99+/Year 38 - Seek and Destroy 3 (size).txt
11 lines, 129 seconds (or faster).
Same principle as existing solution, but using a different worker, permitting horizontal movement instead of vertical, fewer if statements per loop, and fewer directional queries.
Further optimisation may be possible, if completion state can be determined sooner.
> Update Year 38 - Seek and Destroy 3 (size).txt

- Solutions99+/Year 46 - Compulsory Office Romance (both).txt
2i,0s
"Jordan easter egg" by commonnickname
> Update Year 46 - Compulsory Office Romance (both).txt

- SolutionsLowPercent/Year 22 - Number Royale (both)
4i,1s, this solution isn't mine, it's from here https://steamcommunity.com/app/792100/discussions/0/1735463620086845201/
> Create Year 22 - Number Royale (both)

- Solutions99+/Year 52 - The Mode Code (size).txt
> Improve Year 52 - The Mode Code (size) to 15i, 280s

- Solutions99+/Year 54 - Terrain Leveler (size).txt
> Improve Year 54 - Terrain Leveler (size) to 9i, 150+s

- Solutions99+/Year 65 - Defrag Ordered (size).txt
> Improve Year 65 - Defrag Ordered (size) to 14i, 369s

- Solutions99+/Year 63 - Defrag Disordered (size).txt
Improvement on dmr's 11i solution using random pickUp
> Improve Year 63 - Defrag Disordered (size) to 10i, 110s

- Solutions99+/Year 64 - Binary Counter (size).txt
> Improve Year 64 - Binary Counter (size) to 9i, 115s

- Solutions99+/Year 60 - Understaffed Sorting (both).txt
> Improve Year 60 - Understaffed Sorting (size) to 10i, ~570s

- Solutions99+/Year 62 - The Sorting Floor (size).txt
> Improve Year 62 - The Sorting Floor (size) to 14i, ~540s

- Solutions50+/Year 61 - Lazy Pathways (size).txt
> Create Year 61 - Lazy Pathways (size) - 7i, ~967s (50+)

- Solutions99+/Year 48 - Community Training Day (size)
> Create Year 48 - Community Training Day (size)

- Solutions99+/Year 48 - Community Training Day (speed)
> Create Year 48 - Community Training Day (speed)

- Solutions50+/Year 44 - Unique Fashion Party (speed).txt
1s version that doesn't rely on random SET exploit, but not 100% - should work on the iPad version of the game.
> Create Year 44 - Unique Fashion Party (speed).txt (no exploit, 50+)

- Solutions99+/Year 51 - Identify Yourselves (size).txt
> Update Year 51 - Identify Yourselves (size).txt

- Solutions99+/Year 53 - 100 Cubes on the Floor (size).txt
Just messed around with this a bit. It's actually quite interesting how it works.
The topmost worker is fortunately placed next to a data cube. When he does the first step, his mem1 will still be 0, so he can start the chain and doesn't mess anything up.
Every other worker is required to be standing on the first cube of their row at least one cycle without moving at the beginning of the next cycle. Their mem1 is supposed to be + 10 of the row above, but to avoid one if, I just put that +10 at the end of the cycle.
The step left waits for the worker above to be done with 2 datacubes, so that everyone actually waits long enough on their data cube.
The topmost worker is allowed to move without waiting, since his first cube is supposed to stay 0. Otherwise it would become 10.
Also I'm …
> Year 53 - 100 Cubes on the Floor (9 commands, 100%)

- Solutions99+/Year 12 - Unzip (speed).txt
> Update Year 12 - Unzip (speed).txt

- Solutions99+/Year 18 - Uniquely Disposed (speed).txt
> Update Year 18 - Uniquely Disposed (speed).txt

- SolutionsLowPercent/Year 23 - Sorting Hall (speed).txt
not sure about this one. got 14s with it. took like 200 - 300 tries.
> Create Year 23 - Sorting Hall (speed).txt

- Solutions99+/Year 37 - Dangerous Spreadsheeting (size).txt
Small improvement, making it also pass the 32s speed challenge
> Update Year 37 - Dangerous Spreadsheeting (size).txt

- Solutions99+/Year 56 - Local Maximums (size).txt
Credit to Steam user 6e.61.64.6e.65.72.42 https://steamcommunity.com/profiles/76561198062642335
> Improve Year 56 - Local Maximums (size) to 7i

- Solutions99+/Year 31 - Checkerboard Organization (size).txt
> Update Year 31 - Checkerboard Organization (size).txt

- Solutions99+/Year 37 - Dangerous Spreadsheeting (speed).txt
Over 50 tries:
10s: 43x
11s: 7s
> Improve Year 37 - Dangerous Spreadsheeting (speed) to 10-11s

- check_names.py
- Using os.path/os.sep
- Add shebang
- Search files recursive (by option)
- Split check function in smaller units
> check_names.py (Win+Linux)

- Solutions99+/Year 04 - Long Distance Delivery (both).txt
I don't know why, but there is an extra pickup c command here.
> Update Year 04 - Long Distance Delivery (both).txt

- Solutions50+/Year 39 - Printing Etiquette 1 (size).txt
> Create Year 39 - Printing Etiquette 1 (size).txt

- Solutions50+/Year 40 - Printing Etiquette 2 (size).txt
> Create Year 40 - Printing Etiquette 2 (size).txt

- Solutions50+/Year 34 - Seek and Destroy 1 (size).txt
> Create Year 34 - Seek and Destroy 1 (size).txt

- Solutions99+/Year 36 - Seek and Destroy 2 (speed).txt
Improvement upon the current design, optimized 3rd, 5th and 8th workers as well as starting sequence of every other worker.
Over 100 runs:
46s: 78x
47s: 22x
> Improve Year 36 - Seek and Destroy 2 (speed) to 46-47s

- Solutions99+/Year 60 - Understaffed Sorting (speed).txt
Original solution by Steam user Futae Yamagawa, improved by me. ( https://steamcommunity.com/app/792100/discussions/0/1733210552679534467/?ctp=5 )
Over 100 attempts:
68s: 4
69s: 6
70s: 16
71s: 24
72s: 25
73s: 11
74s: 9
75s: 3
76s: 0
77s: 2
average: 71.58
median: 71.5
mode: 72
stdev: ~1.78
> Improve Year 60 - Understaffed Sorting (speed) to 68-77s

- Solutions99+/Year 13 - Injection Sites 2 (size).txt
Credit to Steam user Nomana https://steamcommunity.com/id/Nomana
as far as I know they were the first to post it here: 
https://steamcommunity.com/app/792100/discussions/0/1733210552682850412/
> Improve Year 13 - Injection Sites 2 (size) to 7i, 15s

- Solutions99+/Year 62 - The Sorting Floor (speed).txt
Over 200 tests:
9s:    2x
10s:  66x
11s:  126x
12s:  9x
total average ~10.7s
> Improve Year 62 - The Sorting Floor (speed) to 216i, 9-12s

- SolutionsLowPercent/Year 34 - Seek and Destroy 1 (speed).txt
> Update Year 34 - Seek and Destroy 1 (speed).txt

- Solutions99+/Year 50 - Cubical Communication (speed).txt
> Update Year 50 - Cubical Communication (speed).txt
